apiVersion: delivery.ocm.software/v1alpha1
kind: Resource
metadata:
  name: app-deployment
  namespace: ocm-system
spec:
  interval: 10m0s
  componentVersionRef:
    name: que
    namespace: ocm-system
  resource:
    name: app-deployment
  snapshotTemplate:
    name: app-deployment-snap
